---
title: "UNICEF - Capstone"
subtitle: "Cleaning Data"
author: "Insha, Jasmine, Maddie and Zeena"
format: html
editor: visual
embed-resources: true
editor_options: 
  chunk_output_type: inline
---

## Prelimenaries

```{r}
# Loading Packages
library(tidyverse)
library(janitor)
```

## Loading Data

Loading Survey Data

```{r}
b_dice <- read_csv("data/dice_baseline_clean.csv")
```

## Basic Cleaning

Older codes that were used for basic cleaning for Randomization

```{r}
# change variable names to remove spaces
b_dice <- clean_names(b_dice) 

# make all villages lower case, remove spaces and underscores
b_dice <- b_dice %>%
  mutate(village_name = tolower(trimws(village_name)))

b_dice$health_facility_name <- gsub("_", " ", b_dice$health_facility_name)

# check distinct number of villages and facilities
n_distinct(b_dice$village_name) 

n_distinct(b_dice$health_facility_name) 

# drop individuals who are not caring for children AND are not expecting
b_dice <- b_dice %>%
  filter(if_any
         (c(are_you_currently_expecting_a_child_soon, 
            are_you_currently_caring_for_any_children_under_the_age_of_5_years), 
           ~ . != 0))

```

## New Cleaning

This is also used for creating the codebook.

```{r}
b_dice <- b_dice |>
  select(-x1) 

# Rename
b_dice <- b_dice |>
  rename(enum_id = select_your_name_to_start,
         enum_name = enter_your_id_number_to_access_the_questionaire,
         hh_geocode = take_the_household_geocode,
         phone = do_you_personally_have_a_phone_number,
         language_pref = if_you_can_read_or_were_to_ask_someones_help_to_read_a_message_sent_to_your_phone_which_language_would_you_prefer_to_receive_the_message,
         language_other = please_specify_the_other_language_you_prefer_the_language_to_receive_the_message,
         expecting_child = are_you_currently_expecting_a_child_soon,
         expecting_weeks = if_expectant_how_many_weeks,
         caring_child_under5 = are_you_currently_caring_for_any_children_under_the_age_of_5_years,
         name_nearest_health_facility = what_is_the_name_of_the_nearest_health_facility,
         km_health_facility = what_is_the_estimated_distance_to_health_facility_in_km,
         informal_education = attendance_yes_informal,
         formal_education = attendance_yes_formal,
         no_formal_informal_edu = attendance_neither_formal_or_informal,
         formal_level_education = what_is_your_formal_education_level,
         number_children_under5 = how_many_children_under_the_age_of_five_years_are_living_in_your_household,
         mch_booklet = does_your_child_own_mch_booklet_containing_his_or_her_immunization_status,
         gender_child = please_provide_me_name_child_gender_identity,
         dob_indicated_booklet = is_birth_date_indicated_in_the_booklet,
         dob_in_booklet = what_is_name_child_date_of_birth_indicated_in_the_mch_booklet,
         opv_0d_0w = vaccines_opv_birth_dose,
         opv_dpt_pcv_1d_6w = vaccines_opv_dpt_pcv_1st_dose_at_6_weeks,
         opv_dpt_pcv_2d_10w = vaccines_opv_dpt_pcv_2nd_dose_at_10_weeks,
         opv_dpt_pcv_3d_14w = vaccines_opv_dpt_pcv_3rd_dose_at_14_weeks,
         mr_1d_9m = vaccines_mr_dose_1_9_months,
         mr_2d_18m = vaccines_mr_dose_2_18_months,
         bcg_booklet = from_the_child_booklet_was_name_child_given_bcg_vaccines,
         bcg_date = if_yes_what_is_the_date_recorded_on_the_name_child_booklet_that_he_she_has_received_bcg_vaccines,
        opv_0d_booklet = from_the_child_booklet_was_the_name_child_given_birth_dose_opv,
        opv_0d_date = if_yes_what_is_the_date_recorded_on_name_child_booklet_that_he_has_received_opv_zero_birth_dose_vaccines,
        polio_1d_6w_booklet = from_the_child_booklet_was_name_child_given_1st_dose_polio_vaccine_at_6_weeks_given,
        polio_1d_date = if_yes_what_is_name_child_s_date_given_recorded_for_the1st_dose_polio_vaccine_at_6_weeks,
       polio_2d_10w_booklet = from_the_child_booklet_was_name_child_given_2nd_dose_polio_vaccine_at_10_weeks_given,
       polio_2d_date = if_yes_what_is_the_date_given_recorded_for_the_2nd_dose_polio_vaccine_at_10_weeks_given,
       polio_3d_14w_booklet = from_the_child_booklet_was_name_child_given_3rd_dose_polio_vaccine_at_14_weeks_given ,
       polio_3d_date = if_yes_what_is_the_date_given_recorded_for_the_3rd_dose_polio_vaccine_at_10_weeks_given,
       mr_1d_9m_booklet = from_the_child_booklet_was_name_child_given_mr1_at_9_months,
       mr_1d_date = if_yes_what_is_the_date_given_recorded_for_the_mr1_dose_vaccination,
       mr_2d_18m_booklet = from_the_child_booklet_was_name_child_given_mr2_at_18_months,
       mr_2d_date = if_yes_what_is_the_date_given_recorded_for_the_mr2_dose_vaccination
  )
         
```
